# Generated by Django 5.0 on 2024-05-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AG', 'Agência'), ('AS', 'Atribuir SIM'), ('AI', 'Atribuir IMEI'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DE', 'Desativado'), ('DA', 'Data em Aberto'), ('EA', 'Erro Ativação'), ('ED', 'Erro Desativação'), ('EE', 'Enviar E-mail'), ('ES', 'Em Separação'), ('MB', 'Motoboy'), ('PR', 'Processando'), ('RE', 'Reembolsar'), ('RB', 'Reembolsado'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RT', 'Retirada'), ('VS', 'Verificar SIM')], default='PR', max_length=20),
        ),
    ]
