# Generated by Django 5.0 on 2025-02-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_alter_orders_order_status_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chip-internacional-eua', 'USA'), ('chip-internacional-eua-30-dias', 'USA 30 Dias'), ('chip-internacional-eua-e-canada', 'USA/CANADA'), ('chip-internacional-eua-canada-e-mexico', 'USA/CAN/MEX'), ('chip-internacional-europa-plus', 'EUROPA PLUS'), ('chip-internacional-europa-premium', 'EUROPA PREMIUM'), ('chip-internacional-europa', 'EUROPA'), ('chip-internacional-global', 'GLOBAL'), ('chip-internacional-america-do-sul', 'América do Sul'), ('chip-internacional-america-do-sul-premium', 'América do Sul Premium'), ('plano-voz', 'Plano de Voz')], max_length=50),
        ),
    ]
