# Generated by Django 5.0 on 2025-07-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chip-internacional-eua', 'USA'), ('chip-internacional-eua-30-dias', 'USA 30 Dias'), ('chip-internacional-eua-e-canada', 'USA/CANADA'), ('chip-internacional-eua-canada-e-mexico', 'USA/CAN/MEX'), ('chip-internacional-europa-plus', 'Europa PLUS'), ('chip-internacional-europa-premium', 'Europa PREMIUM'), ('chip-internacional-europa', 'Europa'), ('chip-internacional-global', 'Global'), ('chip-internacional-america-do-sul', 'América do Sul'), ('chip-internacional-america-do-sul-premium', 'América do Sul Premium'), ('chip-internacional-israel-premium', 'Israel PRemium'), ('chip-internacional-tunisia-premium', 'Tunísia Premium'), ('chip-internacional-marrocos-premium', 'Marrocos Premium'), ('chip-internacional-egito-premium', 'Egito Premium'), ('chip-internacional-indonesia-premium', 'Indonésia Premium'), ('chamada-de-voz', 'Plano de Voz')], max_length=50),
        ),
    ]
