# Generated by Django 5.0 on 2025-08-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_alter_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_id_store',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
