# Generated by Django 5.0 on 2025-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_orders_item_id_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_id_store',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
