# Generated by Django 5.0 on 2025-08-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_alter_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='celular_samsung',
            field=models.BooleanField(default=False),
        ),
    ]
