# Generated by Django 5.0 on 2025-09-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chip-internacional-eua', 'USA'), ('chip-internacional-eua-30-dias', 'USA 30 Dias'), ('chip-internacional-eua-e-canada', 'USA/CANADA'), ('chip-internacional-eua-canada-e-mexico', 'USA/CAN/MEX'), ('chip-internacional-europa-plus', 'Europa Plus'), ('chip-internacional-europa', 'Europa'), ('chip-internacional-global', 'Global'), ('chip-internacional-america-do-sul', 'América do Sul'), ('chamada-de-voz', 'Plano de Voz'), ('chip-internacional-europa-ilimitado', 'Europa Ilimitado'), ('chip-internacional-europa-premium', 'Europa Premium'), ('chip-internacional-america-do-sul-premium', 'América do Sul Premium'), ('chip-internacional-israel-premium', 'Israel Premium'), ('chip-internacional-tunisia-premium', 'Tunísia Premium'), ('chip-internacional-marrocos-premium', 'Marrocos Premium'), ('chip-internacional-egito-premium', 'Egito Premium'), ('chip-internacional-indonesia-premium', 'Indonésia Premium'), ('chip-internacional-eua-premium', 'EUA Premium'), ('chip-internacional-africa-premium', 'África Premium'), ('chip-internacional-asia-premium', 'Ásia Premium'), ('chip-internacional-oriente-medio-premium', 'Oriente Médio Premium'), ('chip-internacional-oceania-premium', 'Oceania Premium')], max_length=50),
        ),
    ]
