# Generated by Django 5.0 on 2025-10-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AG', 'Agência'), ('AS', 'Atribuir SIM'), ('AI', 'Atribuir IMEI'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DE', 'Desativado'), ('DA', 'Data em Aberto'), ('EA', 'Erro Ativação'), ('ED', 'Erro Desativação'), ('EE', 'Enviar E-mail'), ('EI', 'Erro Importação'), ('ES', 'Em Separação'), ('MB', 'Motoboy'), ('PR', 'Processando'), ('PV', 'Plano de Voz'), ('RB', 'Reembolsado'), ('RE', 'Reembolsar'), ('RC', 'Reembolso Parcial'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RT', 'Retirada'), ('VS', 'Verificar SIM')], default='PR', max_length=20),
        ),
    ]
