# Generated by Django 5.0 on 2025-12-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='item_id',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
