# Generated by Django 5.0 on 2026-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_alter_orders_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB'), ('1gb', '1GB'), ('2gb', '2GB'), ('ilimitado', 'Ilimitado'), ('20gb', '20GB'), ('50gb', '50GB')], max_length=15),
        ),
    ]
