# Generated by Django 5.0 on 2026-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB'), ('1gb', '1GB'), ('2gb', '2GB'), ('ilimitado', 'Ilimitado'), ('20gb', '20GB'), ('50gb', '50GB'), ('world', 'World')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chip-internacional-eua', 'USA'), ('chip-internacional-eua-30-dias', 'USA 30 Dias'), ('chip-internacional-eua-e-canada', 'USA/CANADA'), ('chip-internacional-eua-canada-e-mexico', 'USA/CAN/MEX'), ('chip-internacional-europa-plus', 'Europa Plus'), ('chip-internacional-europa', 'Europa'), ('chip-internacional-europa-ilimitado', 'Europa Ilimitado'), ('chip-internacional-europa-premium', 'Europa Premium'), ('chip-internacional-europa-1gb-total-05', 'Europa Total'), ('chip-internacional-europa-1gb-total', 'Europa Total'), ('chip-internacional-europa-franquia-total', 'Europa F. Total'), ('chip-internacional-global', 'Global'), ('chip-internacional-global-franquia-total', 'Global F. Total'), ('chip-internacional-america-do-sul', 'América do Sul'), ('chip-internacional-america-do-sul-franquia-total', 'Am. do Sul F. Total'), ('chamada-de-voz', 'Plano de Voz'), ('chip-internacional-america-do-sul-premium', 'América do Sul Premium'), ('chip-internacional-israel-premium', 'Israel Premium'), ('chip-internacional-tunisia-premium', 'Tunísia Premium'), ('chip-internacional-marrocos-premium', 'Marrocos Premium'), ('chip-internacional-egito-premium', 'Egito Premium'), ('chip-internacional-indonesia-premium', 'Indonésia Premium'), ('chip-internacional-eua-premium', 'EUA Premium'), ('chip-internacional-africa-premium', 'África Premium'), ('chip-internacional-africa-franquia-total', 'África F. Total'), ('chip-internacional-asia-premium', 'Ásia Premium'), ('chip-internacional-asia-franquia-total', 'Ásia F. Total'), ('chip-internacional-oriente-medio-premium', 'Oriente Médio Premium'), ('chip-internacional-oceania-premium', 'Oceania Premium')], max_length=50),
        ),
    ]
