# Generated by Django 5.0 on 2026-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_alter_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_sim',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='data_day',
            field=models.CharField(choices=[('500mb-dia', '500MB'), ('1gb', '1GB'), ('2gb', '2GB'), ('ilimitado', 'Ilimitado'), ('20gb', '20GB'), ('50gb', '50GB'), ('world', 'World'), ('10-ilimitado', 'Ilimitado (10)'), ('30-ilimitado', 'Ilimitado (30)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AE', 'Agd. Envio'), ('AO', 'Agd. Operadora'), ('AG', 'Agência'), ('AS', 'Atribuir SIM'), ('AI', 'Atribuir IMEI'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DE', 'Desativado'), ('DA', 'Data em Aberto'), ('EA', 'Erro Ativação'), ('ED', 'Erro Desativação'), ('EE', 'Enviar E-mail'), ('EI', 'Erro Importação'), ('ES', 'Em Separação'), ('MB', 'Motoboy'), ('PR', 'Processando'), ('PV', 'Plano de Voz'), ('RB', 'Reembolsado'), ('RE', 'Reembolsar'), ('RC', 'Reembolso Parcial'), ('RS', 'Reuso'), ('RP', 'Reprocessar'), ('RT', 'Retirada'), ('VS', 'Verificar SIM')], default='PR', max_length=20),
        ),
    ]
