# Generated by Django 5.0 on 2026-06-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_alter_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='msisdn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
