# Generated by Django 5.0 on 2026-06-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_orders_msisdn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='msisdn',
        ),
    ]
