# Generated by Django 6.0.7 on 2026-08-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0066_alter_orders_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.CharField(choices=[('chamada-de-voz', 'Plano de Voz'), ('chip-internacional-eua', 'USA'), ('chip-internacional-eua-30-dias', 'USA 30 Dias'), ('chip-internacional-eua-canada-e-mexico', 'USA/CAN/MEX'), ('chip-internacional-eua-premium', 'EUA Premium'), ('chip-internacional-america-do-norte-franquia-total', 'América do Norte F. Total'), ('chip-internacional-america-do-norte', 'América do Norte'), ('chip-internacional-america-central', 'América Central'), ('chip-internacional-europa', 'Europa'), ('chip-internacional-europa-1gb-total-05', 'Europa Total'), ('chip-internacional-europa-1gb-total', 'Europa Total'), ('chip-internacional-europa-franquia-total', 'Europa F. Total'), ('chip-internacional-europa-ilimitado', 'Europa Ilimitado'), ('chip-fisico-internacional-europa-ilimitado', 'Europa F. Ilimitado'), ('chip-internacional-europa-premium', 'Europa Premium'), ('chip-internacional-global', 'Global'), ('chip-internacional-global-franquia-total', 'Global F. Total'), ('chip-internacional-america-do-sul', 'América do Sul'), ('chip-internacional-america-do-sul-premium', 'América do Sul Premium'), ('chip-internacional-america-do-sul-franquia-total', 'Am. do Sul F. Total'), ('chip-internacional-africa', 'África'), ('chip-internacional-africa-premium', 'África Premium'), ('chip-internacional-africa-franquia-total', 'África F. Total'), ('chip-internacional-asia', 'Ásia'), ('chip-internacional-asia-premium', 'Ásia Premium'), ('chip-internacional-asia-franquia-total', 'Ásia F. Total'), ('chip-internacional-oriente-medio', 'Oriente Médio'), ('chip-internacional-oriente-medio-premium', 'Oriente Médio Premium'), ('chip-internacional-oriente-medio-franquia-total', 'Oriente Médio F. Total'), ('chip-internacional-oceania', 'Oceania'), ('chip-internacional-oceania-premium', 'Oceania Premium'), ('chip-internacional-oceania-franquia-total', 'Oceania F. Total'), ('chip-internacional-caribe-franquia-total', 'Caribe F. Total')], max_length=50),
        ),
    ]
