# Generated by Django 6.0.7 on 2026-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0070_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
