version: '3.8'

services:
  web:
    build: .
    command: /djangoapp/entrypoint.sh
    ports:
      - "80:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"