# Generated by Django 5.0 on 2024-02-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0032_alter_orders_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceNumbers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=15, null=True)),
                ('extension', models.IntegerField()),
                ('number', models.IntegerField()),
                ('password', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('DS', 'Disponível'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('TC', 'Troca')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Número de Voz',
                'verbose_name_plural': 'Número de Voz',
                'db_table': 'voice_numbers',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VoiceCalls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AA', 'Agd. Ativação'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DS', 'Desativado'), ('PR', 'Processando')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('id_voice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='voice_calls.voicenumbers')),
            ],
            options={
                'verbose_name': 'Chamada de Voz',
                'verbose_name_plural': 'Chamadas de Voz',
                'db_table': 'voice_calls',
                'ordering': ['id_item'],
                'managed': True,
            },
        ),
    ]
