# Generated by Django 5.0 on 2024-03-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0002_rename_status_voicenumbers_number_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voicecalls',
            old_name='status',
            new_name='call_status',
        ),
    ]
