# Generated by Django 5.0 on 2024-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0005_voicenumbers_number_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecalls',
            name='call_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DS', 'Desativado'), ('EE', 'Enviar E-mail'), ('PR', 'Processando')], max_length=15),
        ),
    ]
