# Generated by Django 5.0 on 2024-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0006_alter_voicecalls_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicenumbers',
            name='number_status',
            field=models.CharField(choices=[('AT', 'Ativado'), ('CC', 'Cancelado'), ('DS', 'Disponível'), ('IN', 'Indisponível'), ('TC', 'Troca')], default='IN', max_length=15),
        ),
    ]
