# Generated by Django 5.0 on 2025-02-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0007_alter_voicenumbers_number_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicecalls',
            name='activation_date',
            field=models.DateField(default='0001-01-01'),
        ),
        migrations.AddField(
            model_name='voicecalls',
            name='days',
            field=models.IntegerField(default='1'),
        ),
    ]
