# Generated by Django 5.0 on 2025-08-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0008_voicecalls_activation_date_voicecalls_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecalls',
            name='activation_date',
            field=models.DateField(default='2001-01-01'),
        ),
    ]
