# Generated by Django 5.0 on 2025-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0009_alter_voicecalls_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicenumbers',
            name='number_status',
            field=models.CharField(choices=[('AT', 'Ativado'), ('CC', 'Cancelado'), ('DS', 'Disponível'), ('IN', 'Indisponível'), ('TC', 'Troca')], default='DS', max_length=15),
        ),
    ]
