# Generated by Django 5.0 on 2025-09-17 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_alter_orders_product'),
        ('voice_calls', '0010_alter_voicenumbers_number_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecalls',
            name='call_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DS', 'Desativado'), ('EP', 'Erro ao Processar'), ('EE', 'Enviar E-mail'), ('PR', 'Processando'), ('SL', 'Sel. Linha')], max_length=15),
        ),
        migrations.CreateModel(
            name='NotesVoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('type_note', models.CharField(choices=[('S', 'Sistema'), ('P', 'Privada')], default='S', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_voice_notes', to='orders.orders')),
                ('id_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_voice_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notes_voice',
                'ordering': ['-id'],
            },
        ),
    ]
