# Generated by Django 5.0 on 2025-09-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0011_alter_voicecalls_call_status_notesvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesvoice',
            name='id_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_voice_notes', to='voice_calls.voicecalls'),
        ),
    ]
