# Generated by Django 5.0 on 2025-11-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0012_alter_notesvoice_id_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesvoice',
            name='id_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='order_voice_notes', to='voice_calls.voicecalls'),
        ),
    ]
