# Generated by Django 5.0 on 2026-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0013_alter_notesvoice_id_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecalls',
            name='call_status',
            field=models.CharField(choices=[('AA', 'Agd. Ativação'), ('AT', 'Ativado'), ('CC', 'Cancelado'), ('CN', 'Concluido'), ('DS', 'Desativado'), ('EA', 'Erro de Atiivação'), ('ED', 'Erro de Desativação'), ('EP', 'Erro ao Processar'), ('EE', 'Enviar E-mail'), ('PR', 'Processando'), ('SL', 'Sel. Linha')], max_length=15),
        ),
    ]
