# Generated by Django 6.0.7 on 2026-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_calls', '0014_alter_voicecalls_call_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecalls',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
