# Generated by Django 5.0 on 2025-07-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0006_alter_sims_sim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='operator',
            field=models.CharField(choices=[('TM', 'T-Mobile'), ('CM', 'China Mobile'), ('TC', 'Telcom'), ('TI', 'Telcom IMSI')], max_length=20),
        ),
    ]
