# Generated by Django 5.0 on 2025-08-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0007_alter_sims_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='operator',
            field=models.CharField(choices=[('TM', 'T-Mobile'), ('CM', 'China Mobile'), ('TC', 'Telcom'), ('TI', 'Telcom IMSI'), ('MS', 'MoviStar')], max_length=20),
        ),
    ]
