# Generated by Django 5.0 on 2026-01-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0008_alter_sims_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sims',
            name='data',
            field=models.CharField(blank=True, choices=[('20gb', '20GB'), ('50gb', '50GB')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sims',
            name='operator',
            field=models.CharField(choices=[('TM', 'T-Mobile'), ('CM', 'China Mobile'), ('TC', 'Telcom'), ('TI', 'Telcom IMSI'), ('MS', 'MoviStar'), ('OR', 'Orange')], max_length=20),
        ),
    ]
