# Generated by Django 5.0 on 2026-04-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0009_sims_data_alter_sims_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sims',
            name='lpa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
