# Generated by Django 5.0 on 2026-04-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0010_sims_lpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='operator',
            field=models.CharField(choices=[('TM', 'T-Mobile'), ('CM', 'China Mobile'), ('TC', 'Telcom'), ('TI', 'Telcom IMSI'), ('MS', 'MoviStar'), ('OR', 'Orange'), ('AT', 'AT&T')], max_length=20),
        ),
    ]
