# Generated by Django 5.0 on 2026-06-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0011_alter_sims_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sims',
            name='msisdn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
