# Generated by Django 6.0.7 on 2026-08-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sims', '0012_sims_msisdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sims',
            name='operator',
            field=models.CharField(choices=[('TM', 'T-Mobile'), ('CM', 'China Mobile'), ('CMHK', 'CMHK'), ('TC', 'Telcom'), ('TI', 'Telcom IMSI'), ('MS', 'MoviStar'), ('OR', 'Orange'), ('AT', 'AT&T')], max_length=20),
        ),
    ]
